### ISSUE TITLE
1N- tr

### ISSUE THREAD

**Issue by Bryip** [garyleung142857/bridge-system-tex#1]
1N- 2H-2S- 2N*- 3C- 3H* = 4cd fit m?
what if 3C--> 3D

**Comment by garyleung142857** [comment]
I followed some of the developments of Mats Nilsland's 1NT development
<img width="445" alt="Screenshot 2023-08-21 at 2 54 33 PM" src="https://github.com/garyleung142857/bridge-system-tex/assets/40224451/3d397045-5b5b-444a-ba41-077af12bef78">
<img width="443" alt="Screenshot 2023-08-21 at 2 54 48 PM" src="https://github.com/garyleung142857/bridge-system-tex/assets/40224451/3b8736e5-7acc-4ef5-bb8b-b74578920f47">

I have not put those in our system as they look alien. We may follow them if you think it is fun.
I have put Nilsland's notes on out gdrive. Please have a look. There are explanations and summaries (like above screen shots)
