### ISSUE TITLE
Competitive bidding - What is forcing and what is not

### ISSUE THREAD

**Issue by garyleung142857** [garyleung142857/bridge-system-tex#10]
I think I have brought up this a couple of times
In normal sysytems, we usually play 1/3 Force 2 NF, or new suit F.

I suggest that 1X / 2m / 3M Force, 2M / 3m NF. Is it playable? Any potential issues?

I treat 2m / 2M differently becoz 2m leaves more space than 2M.
More space = better for constructive bidding

Similar effects can be observed when playing fantunes: 2C is good for our constructive bidding, while 2S is best for offensive, but we cannot resolve the shape very well

---

Mainly these 2 sequences

- Sth (Sth) Sth
- (Sth) Sth (P) Sth

"2m forcing" can be assigned sth Artificial

**Comment by Bryip** [comment]
actually work, just try it out.
(potential disadv: some may only willing to compete 2m but now need compete 3m with one hand, normally can compete 2m and let partner choose raise or not;
3M Force though less space slam try, but no harm, enough actually [just like after 2 over 1 fit 3 level])
