### ISSUE TITLE
1N open (casual discussion)

### ISSUE THREAD

**Issue by Bryip** [garyleung142857/bridge-system-tex#11]
1N- 3M: [now one m ST]
heard an interesting one (from Wolpert the youtuber maybe)
3H= 3154/ 3145 GF, 3S= 1354/ 1345 GF, seems quite common in US (not sure about others)

**Comment by Bryip** [comment]
1N- 3N/ 4M (game)

me think play them as to play quite a waste, can think of new combination there idk

some variation:
maybe 3N one m ST solving the above issue, free out 4m (both M? gerber?) and 4S (Quan with 5cd m/ Quan with 4+C (4N with 4+D))

**Comment by garyleung142857** [comment]
> 3H= 3154/ 3145 GF, 3S= 1354/ 1345 GF, seems quite common in US (not sure about others)

Actually Kenny and I played this before, but we think that we just boil 3N with bare GF hand, or 2S (size ask) then 3M to show such hands.

**Comment by garyleung142857** [comment]
> 1N- 3N / 4M (game)
> me think play them as to play quite a waste, can think of new combination there idk

I think 3N as Nat is good to be used as boiling game (esp in desperate IMP deficit situations)
1N 4M is not necessary though, as we have sa texas.

**Comment by garyleung142857** [comment]
Actually I have thought of sth like this:

1N - ?
3H: 4-5 spades. COG (3S = 3 spade)
3S: =5 hearts. COG
3N: =4 hearts. COG

So need not stayman for minimal GF hands

**Comment by garyleung142857** [comment]
Another idea:
1N - ?
3H: 4=S only GF, or C slam try. Puppet to 3S
3S: Puppet to 3N. Could be to play in 3N, or D slam try.
3N: 4=H. COG

1N - 3H; 3S - ?
3N: 4=S COG
Other: C slam try

1N - 3S; 3N - ?
Pass: To play
Other: D slam try

@Bryip

**Comment by Bryip** [comment]
> Another idea: 1N - ? 3H: 4=S only GF, or C slam try. Puppet to 3S 3S: Puppet to 3N. Could be to play in 3N, or D slam try. 3N: 4=H. COG
> 
> 1N - 3H; 3S - ? 3N: 4=S COG Other: C slam try
> 
> 1N - 3S; 3N - ? Pass: To play Other: D slam try
> 
Can wor, love this set

**Comment by garyleung142857** [comment]
Bad thing is that this passed 3N for ST

**Comment by Bryip** [comment]
So we now giving up 54M inv (and 44M inv may miss the chance to land in 3H) ?

**Comment by Bryip** [comment]
1N- 3D: including hands like 3145 ? or only 4144/ 4054

**Comment by garyleung142857** [comment]
> So we now giving up 54M inv (and 44M inv may miss the chance to land in 3H) ?

Can find other major fit if opener accepts invite, else likely to be in 2N

> 1N- 3D: including hands like 3145 ? or only 4144/ 4054

Go through 1N - 2C; 2D - 3C, but those should be strong enough for 5m if 3N is really bad
