### ISSUE TITLE
Quan with 5cdm after 2N open (or 2C then 2N)

### ISSUE THREAD

**Issue by Bryip** [garyleung142857/bridge-system-tex#2]
as direct 4level bid used as 4 way tr,
(maybe) 2N- 3C- 3 any- 4H/S = 5cd C/D Quan

**Comment by garyleung142857** [comment]
5m332 has at least one 3-card major, so responder can bid 3C muppet stayman first, then continue the bidding

Again, Nilsland's 2NT notes is in the drive. Can have a look
