### ISSUE TITLE
2C (18-19) Open

### ISSUE THREAD

**Issue by Bryip** [garyleung142857/bridge-system-tex#24]
2C- no texas? 
2C- 3M/ 4D seems overlapping, if 55m shdnt bid 3M show shortage first?

**Comment by Bryip** [comment]
Contested Auction:
2C - (X) - ?
now basically obligated to X --> after some bids land 2N?
need define what opp X could be (now intuitively C, as opp wont give you the chance for a easy 2CX contract) and think of defence

**Comment by garyleung142857** [comment]
> 2C- no texas?
> 2C- 3M/ 4D seems overlapping, if 55m shdnt bid 3M show shortage first?

Right, then I switch to
2C - ?
3N: Does not exist
4m: SA Texas
4H: ST in C
4S: ST in D

I know I can use normal texas transfer to keep 3N as C ST, but we are using SA Texas for 2N opening... don't wanna confuse everyone.

**Comment by garyleung142857** [comment]
> if weak hand (0-5) can only pass with C tolerance or even C suit?
If responder has a 5-card suit 0-5, he can bid 2D/2H/2S, NF.

> need define what opp X could be
Too bad the system notes I obtained did not specified this
