### ISSUE TITLE
Resolving Major Raises with possibility of 7-card fit

### ISSUE THREAD

**Issue by garyleung142857** [garyleung142857/bridge-system-tex#5]
After some sequences where fit at 2M could be based on 7-card fits, e.g.:
- 1D (P) 1H (1S); 2H

(1) We need to have ways to resolve the above sequence if we explore game
(2) Think of a generalization to all 2M raises

**Comment by Bryip** [comment]
is that called spiral 2M?
anyway must understand raising with 3cd basically means hcp not in opp suit (e.g. S, like X/XX/ XXX in S, even in free run, often imagine/ assume opp has oM) greatly suggest playing in 2M (while the hand is shapeful and/or has some source of trick like 5cd m)

Ways to check:
No idea, if always 2N I+ then use 2N, if use 2M+1 then 2S for H fit, 2N for S fit
Real no comment for the response (as opener has capped range so sidan)
[even play ogust dou duk, sidan :) ]

**Comment by Bryip** [comment]
Side note: Frequency of spiral raise
Tbh not as common as I thought, not very often to be at the suitable position with that hand
