### ISSUE TITLE
1C - 1N

### ISSUE THREAD

**Issue by garyleung142857** [garyleung142857/bridge-system-tex#9]
## Issue 1
1C - 1N; 2C - 2X
1N: Bal or C. GF
2C: 12-14 Bal
2X: 5C 4X

As tested out before, 2N = shape ask is unnecessary revealing responder's (likely to be declarer's) hand.

How about here, we play:
2Y: Natural. 4 cards
2N: Natural. Unfit. 12-14. Catch-all
3C: Fit C
3X: Fit X
Others: Undefined

## Issue 2
1C - 1N; 2D/H/S

I think Resp can still use Type B asking bid here. Useful if resp is non-min and want to try thin slam

**Comment by Bryip** [comment]
> How about here, we play: 2Y: Natural. 4 cards 2N: Natural. Unfit. 12-14. Catch-all 3C: Fit C 3X: Fit X Others: Undefined
ok, no comment lol


> 1C - 1N; 2D/H/S
> I think Resp can still use Type B asking bid here. Useful if resp is non-min and want to try thin slam
> can, but BAB ask max or min effect not that significant (11-12/ 13-14) lolll

**Comment by garyleung142857** [comment]
> can, but BAB ask max or min effect not that significant (11-12/ 13-14) lolll

Not really. If opener is unbal, he can have any strength (11-22)
